[General]
  snippetfile = "~/.config/pet/snippet.toml"
  editor = "vim"
  column = 40
  selectcmd = "peco"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  public = false
  auto_sync = false
